# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://dpoulopoulos.github.io/deep_animator/"

git_url = "https://github.com/dpoulopoulos/deep_animator/tree/master/"

def custom_doc_links(name): return None
