# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"SynchronizedBatchNorm2d": "batchnorm.ipynb",
         "deep_animate": "cli.ipynb",
         "FutureResult": "comm.ipynb",
         "SlavePipe": "comm.ipynb",
         "SyncMaster": "comm.ipynb",
         "DenseMotionNetwork": "modules_dense_motion.ipynb",
         "OcclusionAwareGenerator": "modules_generator.ipynb",
         "KPDetector": "modules_kp_detector.ipynb",
         "DownBlock2d": "modules_utils.ipynb",
         "UpBlock2d": "modules_utils.ipynb",
         "Encoder": "modules_utils.ipynb",
         "Decoder": "modules_utils.ipynb",
         "Hourglass": "modules_utils.ipynb",
         "AntiAliasInterpolation2d": "modules_utils.ipynb",
         "make_coordinate_grid": "modules_utils.ipynb",
         "kp2gaussian": "modules_utils.ipynb",
         "gaussian2kp": "modules_utils.ipynb",
         "SameBlock2d": "modules_utils.ipynb",
         "ResBlock2d": "modules_utils.ipynb",
         "CallbackContext": "replicate.ipynb",
         "execute_replication_callbacks": "replicate.ipynb",
         "DataParallelWithCallback": "replicate.ipynb",
         "load_checkpoints": "utils.ipynb",
         "normalize_kp": "utils.ipynb",
         "animate": "utils.ipynb"}

modules = ["sync_batchnorm/batchnorm.py",
           "cli.py",
           "sync_batchnorm/comm.py",
           "modules/dense_motion.py",
           "modules/generator.py",
           "modules/kp_detector.py",
           "modules/utils.py",
           "sync_batchnorm/replicate.py",
           "utils.py"]

doc_url = "https://dpoulopoulos.github.io/deep_animator/"

git_url = "https://github.com/dpoulopoulos/deep_animator/tree/master/"

def custom_doc_links(name): return None
