# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/utils.ipynb (unless otherwise specified).

__all__ = ['load_checkpoints']

# Cell
import yaml
import torch
import torch.nn as nn

from typing import Tuple

# Cell
def load_checkpoints(config_path: str, checkpoint_path: str, device: str = 'cpu') \
                     -> Tuple[torch.nn.Module, torch.nn.Module]:
    # load configuration
    with open(config_path) as f:
        config = yaml.load(f, Loader=yaml.FullLoader)

    generator = OcclusionAwareGenerator(**config['model_params']['generator_params'],
                                        **config['model_params']['common_params'])
    generator.to(device)

#     kp_detector = KPDetector(**config['model_params']['kp_detector_params'],
#                              **config['model_params']['common_params'])
#     kp_detector.cuda()

#     checkpoint = torch.load(checkpoint_path)
#     generator.load_state_dict(checkpoint['generator'])
#     kp_detector.load_state_dict(checkpoint['kp_detector'])

#     generator = DataParallelWithCallback(generator)
#     kp_detector = DataParallelWithCallback(kp_detector)

#     generator.eval()
#     kp_detector.eval()

#     return generator, kp_detector