# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/modules_kp_detector.ipynb (unless otherwise specified).

__all__ = []

# Cell
import torch
import torch.nn.functional as F

from torch import nn

from .utils import Hourglass, AntiAliasInterpolation2d